@echo off
echo "Building DLL patches (EN > KR)..."
"xdelta3.exe" -e -f -s "%~dp0files_en\Launcher.dll" 	"%~dp0files_kr\Launcher.dll" 	"%~dp0e2k.Launcher.dll.vcdiff"
"xdelta3.exe" -e -f -s "%~dp0files_en\WhiteDay.dll" 	"%~dp0files_kr\WhiteDay.dll" 	"%~dp0e2k.WhiteDay.dll.vcdiff"
"xdelta3.exe" -e -f -s "%~dp0files_en\WhiteDay_p4.dll"	"%~dp0files_kr\WhiteDay_p4.dll"	"%~dp0e2k.WhiteDay_p4.dll.vcdiff"
"xdelta3.exe" -e -f -s "%~dp0files_en\whiteday.exe" 	"%~dp0files_kr\whiteday.exe" 	"%~dp0e2k.whiteday.exe.vcdiff"
"xdelta3.exe" -e -f -s "%~dp0files_en\mod_beanbag.dll" 	"%~dp0files_kr\mod_beanbag.dll" "%~dp0e2k.mod_beanbag.dll.vcdiff"
echo "Done."

echo "Building DLL patches (KR > EN)..."
"xdelta3.exe" -e -f -s "%~dp0files_kr\Launcher.dll" 	"%~dp0files_en\Launcher.dll" 	"%~dp0k2e.Launcher.dll.vcdiff"
"xdelta3.exe" -e -f -s "%~dp0files_kr\WhiteDay.dll" 	"%~dp0files_en\WhiteDay.dll" 	"%~dp0k2e.WhiteDay.dll.vcdiff"
"xdelta3.exe" -e -f -s "%~dp0files_kr\WhiteDay_p4.dll" 	"%~dp0files_en\WhiteDay_p4.dll" "%~dp0k2e.WhiteDay_p4.dll.vcdiff"
"xdelta3.exe" -e -f -s "%~dp0files_kr\whiteday.exe" 	"%~dp0files_en\whiteday.exe" 	"%~dp0k2e.whiteday.exe.vcdiff"
"xdelta3.exe" -e -f -s "%~dp0files_kr\mod_beanbag.dll" 	"%~dp0files_en\mod_beanbag.dll" "%~dp0k2e.mod_beanbag.dll.vcdiff"
echo "Done."