//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDLaunch.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WDLaunch.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _140 {
            get {
                object obj = ResourceManager.GetObject("_140", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _140_hover {
            get {
                object obj = ResourceManager.GetObject("_140_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anti-Aliasing.
        /// </summary>
        public static string AATerm {
            get {
                return ResourceManager.GetString("AATerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dgVoodoo Anti-Aliasing (MSAA)
        ///- Smooths out edges..
        /// </summary>
        public static string AATip {
            get {
                return ResourceManager.GetString("AATip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ✱.
        /// </summary>
        public static string AdminModeTerm {
            get {
                return ResourceManager.GetString("AdminModeTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin mode.
        /// </summary>
        public static string AdminModeTerm_MoreSettings {
            get {
                return ResourceManager.GetString("AdminModeTerm_MoreSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to Windows UAC, running White Day without admin privileges changes
        ///the location of your save files and screenshots to &apos;%localappdata%\VirtualStore&apos;
        ///instead of the main directory..
        /// </summary>
        public static string AdminModeTip {
            get {
                return ResourceManager.GetString("AdminModeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always Admin.
        /// </summary>
        public static string AlwaysAdminTerm {
            get {
                return ResourceManager.GetString("AlwaysAdminTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option will cause the launcher to always open as admin..
        /// </summary>
        public static string AlwaysAdminTip {
            get {
                return ResourceManager.GetString("AlwaysAdminTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White Day needs to be run at least once before this option can be enabled..
        /// </summary>
        public static string AutoLaunchDeviceSettingsNotConfiguredWarning {
            get {
                return ResourceManager.GetString("AutoLaunchDeviceSettingsNotConfiguredWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Launch.
        /// </summary>
        public static string AutoLaunchTerm {
            get {
                return ResourceManager.GetString("AutoLaunchTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using Direct Launch will bypass the official launcher and launch the game directly.
        ///- To use this feature, it&apos;s necessary to run the game at least once in order to configure display settings.
        ///- With this enabled you can also access console mode by holding ALT..
        /// </summary>
        public static string AutoLaunchTip {
            get {
                return ResourceManager.GetString("AutoLaunchTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelTerm {
            get {
                return ResourceManager.GetString("CancelTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture Mouse.
        /// </summary>
        public static string CaptureMouseTerm {
            get {
                return ResourceManager.GetString("CaptureMouseTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forces the mouse into the application window..
        /// </summary>
        public static string CaptureMouseTip {
            get {
                return ResourceManager.GetString("CaptureMouseTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check For Updates.
        /// </summary>
        public static string CheckForUpdatesTerm {
            get {
                return ResourceManager.GetString("CheckForUpdatesTerm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        public static string UpdateAvailableTitle {
            get {
                return ResourceManager.GetString("UpdateAvailableTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New version {0} available! Update now?.
        /// </summary>
        public static string UpdateAvailableMessage {
            get {
                return ResourceManager.GetString("UpdateAvailableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close ZeroTier.
        /// </summary>
        public static string CloseZTTerm {
            get {
                return ResourceManager.GetString("CloseZTTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZeroTier is currently open. Click here to close it..
        /// </summary>
        public static string CloseZTTip {
            get {
                return ResourceManager.GetString("CloseZTTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Network.
        /// </summary>
        public static string CreateTerm {
            get {
                return ResourceManager.GetString("CreateTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d3d8to9 by crosire.
        /// </summary>
        public static string CROTip {
            get {
                return ResourceManager.GetString("CROTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses a wrapper to convert the game&apos;s Direct3D graphics API to D3D 11.
        ///- Fixes compatibility issues as well as offering other enhancements.
        ///- Fixes the &apos;fast game speed&apos; issue.
        ///
        /// Select which wrapper to use under &quot;More Settings&quot; below..
        /// </summary>
        public static string D3D8WrapperTip {
            get {
                return ResourceManager.GetString("D3D8WrapperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default to Windowed.
        /// </summary>
        public static string DefaultWindowedTerm {
            get {
                return ResourceManager.GetString("DefaultWindowedTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Causes White Day to open in windowed mode by default..
        /// </summary>
        public static string DefaultWindowedTip {
            get {
                return ResourceManager.GetString("DefaultWindowedTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteTerm {
            get {
                return ResourceManager.GetString("DeleteTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dgVoodoo2 by Dégé.
        /// </summary>
        public static string DGVTip {
            get {
                return ResourceManager.GetString("DGVTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download progress:.
        /// </summary>
        public static string DownloadProgressTerm {
            get {
                return ResourceManager.GetString("DownloadProgressTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string EnglishTerm {
            get {
                return ResourceManager.GetString("EnglishTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borderless Fullscreen.
        /// </summary>
        public static string FakeFullscreenAttrTerm {
            get {
                return ResourceManager.GetString("FakeFullscreenAttrTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forces borderless/fake fullscreen mode with a screen-size window..
        /// </summary>
        public static string FakeFullscreenAttrTip {
            get {
                return ResourceManager.GetString("FakeFullscreenAttrTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix Locale.
        /// </summary>
        public static string FixLocaleTerm {
            get {
                return ResourceManager.GetString("FixLocaleTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start ZeroTier.
        /// </summary>
        public static string InstallLaunchZTTerm {
            get {
                return ResourceManager.GetString("InstallLaunchZTTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installs or opens ZeroTier, which is necessary to play Oh! Jaemi online.
        ///- Players in the same ZeroTier network can connect to each other via virtual LAN..
        /// </summary>
        public static string InstallLaunchZTTip {
            get {
                return ResourceManager.GetString("InstallLaunchZTTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Network.
        /// </summary>
        public static string JoinTerm {
            get {
                return ResourceManager.GetString("JoinTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string LangButtonTip {
            get {
                return ResourceManager.GetString("LangButtonTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Network.
        /// </summary>
        public static string LeaveTerm {
            get {
                return ResourceManager.GetString("LeaveTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runs the game with a Korean locale.
        ///- Essential if your system locale is not set to Korean.
        ///- Fixes many issues such as missing UI and random floating objects..
        /// </summary>
        public static string LocaleEmulatorTip {
            get {
                return ResourceManager.GetString("LocaleEmulatorTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select which monitor to play White Day on..
        /// </summary>
        public static string MonitorSelectTip {
            get {
                return ResourceManager.GetString("MonitorSelectTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor.
        /// </summary>
        public static string MonitorTerm {
            get {
                return ResourceManager.GetString("MonitorTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Settings.
        /// </summary>
        public static string MoreSettingsTerm {
            get {
                return ResourceManager.GetString("MoreSettingsTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Floating Head.
        /// </summary>
        public static string NoFloatingHeadTerm {
            get {
                return ResourceManager.GetString("NoFloatingHeadTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevents the floating head ghost from spawning..
        /// </summary>
        public static string NoFloatingHeadTip {
            get {
                return ResourceManager.GetString("NoFloatingHeadTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No HUD.
        /// </summary>
        public static string NoHUDTerm {
            get {
                return ResourceManager.GetString("NoHUDTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes the HUD for cinematic shots..
        /// </summary>
        public static string NoHUDTip {
            get {
                return ResourceManager.GetString("NoHUDTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Janitor.
        /// </summary>
        public static string NoJanitorTerm {
            get {
                return ResourceManager.GetString("NoJanitorTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prevents the janitor from spawning..
        /// </summary>
        public static string NoJanitorTip {
            get {
                return ResourceManager.GetString("NoJanitorTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string NoTerm {
            get {
                return ResourceManager.GetString("NoTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ohjaemi {
            get {
                object obj = ResourceManager.GetObject("ohjaemi", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ohjaemi_hover {
            get {
                object obj = ResourceManager.GetObject("ohjaemi_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh! Jaemi.
        /// </summary>
        public static string OhJaemiTerm {
            get {
                return ResourceManager.GetString("OhJaemiTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ojbg {
            get {
                object obj = ResourceManager.GetObject("ojbg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the screenshots folder.
        ///Note: The location is different depending on whether the game is run in admin mode..
        /// </summary>
        public static string OpenCaptureDirTip {
            get {
                return ResourceManager.GetString("OpenCaptureDirTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the main directory..
        /// </summary>
        public static string OpenMainDirTip {
            get {
                return ResourceManager.GetString("OpenMainDirTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the saves folder.
        ///Note: The location is different depending on whether the game is run in admin mode..
        /// </summary>
        public static string OpenSavesDirTip {
            get {
                return ResourceManager.GetString("OpenSavesDirTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string OptionsTerm {
            get {
                return ResourceManager.GetString("OptionsTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peaceful Janitor.
        /// </summary>
        public static string PeacefulJanitorTerm {
            get {
                return ResourceManager.GetString("PeacefulJanitorTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Causes the janitor to be friendly to the player..
        /// </summary>
        public static string PeacefulJanitorTip {
            get {
                return ResourceManager.GetString("PeacefulJanitorTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates the current privilege level of the program..
        /// </summary>
        public static string PrivilegeIndicatorTip {
            get {
                return ResourceManager.GetString("PrivilegeIndicatorTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quieter Alarms.
        /// </summary>
        public static string QuieterAlarmsTerm {
            get {
                return ResourceManager.GetString("QuieterAlarmsTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quietens the alarms in the workshop..
        /// </summary>
        public static string QuieterAlarmsTip {
            get {
                return ResourceManager.GetString("QuieterAlarmsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relaunch As Admin.
        /// </summary>
        public static string RelaunchAsAdminTerm {
            get {
                return ResourceManager.GetString("RelaunchAsAdminTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-opens the launcher with admin privileges..
        /// </summary>
        public static string RelaunchAsAdminTip {
            get {
                return ResourceManager.GetString("RelaunchAsAdminTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Wrapper:.
        /// </summary>
        public static string SelectWrapperTerm {
            get {
                return ResourceManager.GetString("SelectWrapperTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Direct3D wrapper method..
        /// </summary>
        public static string SetWrapperTip {
            get {
                return ResourceManager.GetString("SetWrapperTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stbg {
            get {
                object obj = ResourceManager.GetObject("stbg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretched AR Scaling.
        /// </summary>
        public static string StretchedARScalingTerm {
            get {
                return ResourceManager.GetString("StretchedARScalingTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When playing at a non-native resolution, the game&apos;s display output
        ///will be stretched rather than changing your monitor&apos;s resolution.
        ///Aspect ratio is respected. Results in smooth alt-tabbing at all resolutions..
        /// </summary>
        public static string StretchedARScalingTip {
            get {
                return ResourceManager.GetString("StretchedARScalingTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texture Filtering.
        /// </summary>
        public static string TexFiltTerm {
            get {
                return ResourceManager.GetString("TexFiltTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dgVoodoo Texture Filtering
        ///- Enhances textures at angles..
        /// </summary>
        public static string TexFiltTip {
            get {
                return ResourceManager.GetString("TexFiltTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Windowed Mode.
        /// </summary>
        public static string ToggleScreenModeTerm {
            get {
                return ResourceManager.GetString("ToggleScreenModeTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows you to toggle windowed mode with Alt+Enter..
        /// </summary>
        public static string ToggleScreenModeTip {
            get {
                return ResourceManager.GetString("ToggleScreenModeTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap transpbg {
            get {
                object obj = ResourceManager.GetObject("transpbg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tweaks.
        /// </summary>
        public static string TweaksTerm {
            get {
                return ResourceManager.GetString("TweaksTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock All Difficulties.
        /// </summary>
        public static string UnlockAllDifficultiesTerm {
            get {
                return ResourceManager.GetString("UnlockAllDifficultiesTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlocks the Hard and Hell difficulty modes..
        /// </summary>
        public static string UnlockAllDifficultiesTip {
            get {
                return ResourceManager.GetString("UnlockAllDifficultiesTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock All Options.
        /// </summary>
        public static string UnlockAllOptionsTerm {
            get {
                return ResourceManager.GetString("UnlockAllOptionsTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlocks the Alternate Skins, Janitor Disguise and Low Quality Voices options..
        /// </summary>
        public static string UnlockAllOptionsTip {
            get {
                return ResourceManager.GetString("UnlockAllOptionsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User mode.
        /// </summary>
        public static string UserModeTerm {
            get {
                return ResourceManager.GetString("UserModeTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently installed version of White Day Repackaged.
        ///Click to check for updates..
        /// </summary>
        public static string VersionTip {
            get {
                return ResourceManager.GetString("VersionTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncs frame rate with refresh rate of your monitor.
        ///Enable if you get visual tearing..
        /// </summary>
        public static string VSyncTip {
            get {
                return ResourceManager.GetString("VSyncTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string WarningTerm {
            get {
                return ResourceManager.GetString("WarningTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap wdbg {
            get {
                object obj = ResourceManager.GetObject("wdbg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] wdhelper {
            get {
                object obj = ResourceManager.GetObject("wdhelper", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap whitedayexe {
            get {
                object obj = ResourceManager.GetObject("whitedayexe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap whitedayexe_hover {
            get {
                object obj = ResourceManager.GetObject("whitedayexe_hover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrap Direct3D.
        /// </summary>
        public static string WrapD3DTerm {
            get {
                return ResourceManager.GetString("WrapD3DTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrapper Settings.
        /// </summary>
        public static string WrapperTerm {
            get {
                return ResourceManager.GetString("WrapperTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YesTerm {
            get {
                return ResourceManager.GetString("YesTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string ZTActiveTerm {
            get {
                return ResourceManager.GetString("ZTActiveTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates if ZeroTier is currently running..
        /// </summary>
        public static string ZTActivityTip {
            get {
                return ResourceManager.GetString("ZTActivityTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens ZeroTier Central in your web browser. There you can create a new
        ///network via your account. Players who join your network can join any games
        ///you host over the internet..
        /// </summary>
        public static string ZTCreateNetworkTip {
            get {
                return ResourceManager.GetString("ZTCreateNetworkTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string ZTInactiveTerm {
            get {
                return ResourceManager.GetString("ZTInactiveTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the network ID to join:.
        /// </summary>
        public static string ZTJoinNetworkPromptDesc {
            get {
                return ResourceManager.GetString("ZTJoinNetworkPromptDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Network.
        /// </summary>
        public static string ZTJoinNetworkPromptTitle {
            get {
                return ResourceManager.GetString("ZTJoinNetworkPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join a ZeroTier network. Once you&apos;ve joined someone&apos;s network,
        ///you can join any games they host over the internet..
        /// </summary>
        public static string ZTJoinNetworkTip {
            get {
                return ResourceManager.GetString("ZTJoinNetworkTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a network to leave..
        /// </summary>
        public static string ZTLeaveNetworkNullWarning {
            get {
                return ResourceManager.GetString("ZTLeaveNetworkNullWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave the selected ZeroTier network..
        /// </summary>
        public static string ZTLeaveNetworkTip {
            get {
                return ResourceManager.GetString("ZTLeaveNetworkTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network ID.
        /// </summary>
        public static string ZTNetworkIDTerm {
            get {
                return ResourceManager.GetString("ZTNetworkIDTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ZTNetworkNameTerm {
            get {
                return ResourceManager.GetString("ZTNetworkNameTerm", resourceCulture);
            }
        }
    }
}
